# Generated by Django 4.0.1 on 2022-01-15 18:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Compañias',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Placa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('operador', models.CharField(max_length=50)),
                ('hora_inicio_descarga', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('programado', models.BooleanField(default=True)),
                ('compania', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedor.compania')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedor.material')),
                ('placa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedor.placa')),
                ('recibido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedor.responsable')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable', to='proveedor.responsable')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
